
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kptcatspqbrccuiqskfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwdGNhdHNwcWJyY2N1aXFza2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDk1NTksImV4cCI6MjA2NTYyNTU1OX0.wqjoHQLN9-r51E-qCLTWrL5AevG8qKEppAw50toJ45w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
